### ISSUE TITLE
[Development]: Thirst Mechanics

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#127]
### Discussed in https://github.com/MCreator-Examples/Tale-of-Biomes/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **northwesttreesgaming** January 21, 2024</sup>
# Overview
Eating food is important but drinking is way more important as it can cause death over time.

## Dimensions
- [ ] Eldenmoor
- [ ] Config Support ???

## Consumable Fluids
Fluids offer custom saturation for hydronation for the player and in some cases status effects.

### Juice Ideas
- [ ] Juice (Apple)
- [ ] Juice (Cherry)
- [ ] Juice (Lemon)
- [ ] Juice (Orange)
- [ ] Juice (Peach)
- [ ] Juice (Pear)
- [ ] Juice (Plum)

### Water Ideas
- [ ] Water (Clean)
- [ ] Water (Raw)

### Wine Ideas
- [ ] Wine (Apple)
- [ ] Wine (Cherry)
- [ ] Wine (Lemon)
- [ ] Wine (Orange)
- [ ] Wine (Peach)
- [ ] Wine (Pear)
- [ ] Wine (Plum)

### Other Ideas
- [ ] Beer (Hops)
- [ ] Cedar (Apple)
- [ ] Mead (Honey)
- [ ] Rum (Sugar)

## Player Fluid Saturation
Saturation acts as the general time until the fluid bar starts to decrease in its main level.

### Decreasing Ideas
- [ ] Drinking fluids with bad effects.
- [ ] Placing/breaking blocks
- [ ] Player control motion ( > 0.25 )
- [ ] Player damage
- [ ] Temperature ( < 10  OR > 20 )
- [ ] Using items

### Increasing Ideas
- [ ] Clean drinks
- [ ] Status effects
- [ ] Some foods such as soups.

## Player Fluid
Player Fluid controls the HUD icons which range from zero to twenty (0-20).
When the bar reaches zero the player will start to take some dehydrated damage.

### Tasks
- [x] Custom Damage
- [x] Overlay HUD for thirst

## Config
Config should be made to control some settings as mentioned below.

### Settings
- [ ] Damage Taken
- [ ] Damage Time
- [ ] Enabled Dimensions
- [ ] Max Safe Temperature
- [ ] Min Safe Temperature
- [ ] Min Player Control Speed
- [ ] Max Saturation
- [ ] Saturation Time</div>
