### ISSUE TITLE
[Development]: Block of Phosphorite

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#17]
# Overview
A light source made from Phosphorite. The block provides a light level of 10. 
The block also requires the player to mine the block with a pickaxe.

## Todo List
- [ ] Make the assets
- [ ] Create a DECORATION TABLE
- [ ] Create a recipe for the decoration table
- [ ] Make the block provide 10 points of light.
