### ISSUE TITLE
[Development]: Animal Troughs

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#26]
# EARLY GAME
An entity that can be used by other entities to get food from. 
Hay bales can be placed into Animal Troughs to feed animals.

- Requires farming skill level 2 to interact with the entity.
- [Hay Bales](https://github.com/MCreator-Examples/Tale-of-Biomes/issues/27) can be traded or bought early-game.
- One bale will fill the trough to the full capacity.
- Each time the entity uses the animal it will deal one damage point to the item in its inventory.

## Todo List
- [ ] Make assets for the entity states (filled/empty)
- [ ] Added pathfinding mechanics to FARM ENTITIES.
- [ ] Added damage system for the entity's inventory.
