### ISSUE TITLE
[Development]: Hunger Mechanics

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#34]
# Overview
Players will get hungry the more they do tasks in the world.
eg farming, crafting, mining, etc.

# Tasks
- [ ] Make this feature only apply to Eldenmoor
- [ ] Make it so activities can drain the food bar over time.
- [ ] Make it so it's affected by difficulty.

# Activitities
- Skill-based activities, such as farming, and crafting at specific stations.
- General activities such as building, and breaking blocks.
