### ISSUE TITLE
[Development]: Basic Tool Table

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#38]
# Overview
- A crafting block that is used to make Level 2 tools (Stone).
- Can be used to make tool heads and tool grips.
- Tool heads and grips can be combined to make tool types.
- Durability combines the tool head material with the tool grip material to set the overall tool durability.

# Todo
- [x] Create Block
- [x] Create Tool Head Recipes
- [x] Create Tool Grip Recipes
- [x] Create Tool Recipes
