### ISSUE TITLE
[Development]: Mower

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#45]
# Overview
An entity that can be driven that will mow tall grass around the entity to straw.
This is a late-game feature that can be unlocked by reaching farming activities.

## Todo List
- [ ] Mower can be crafted at Farming Skill Level 5.
- [ ] Mowers provide a ridable solution for cutting grass.
- [ ] Mowers require fuel to operate or if upgraded to electric energy.
