### ISSUE TITLE
[Development]: Farmer Traders

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#46]
# Overview
Farmer Traders can appear around the player randomly.
Traders in general are random and sell goods that are relevant to skill sets like farming.

## Todo List
- [ ] Make assets for the Farmer Trader.
- [ ] Make spawning and despawning mechanics for the Farmer Trader.
- [ ] Add a common trade for Sickles.
- [ ] Add a common trade for Scythes.
- [ ] Add a common trade for Quicklime
- [ ] Add a common trade for random seeds
- [ ] Add a common trade for Hoes
- [ ] Add a common trade for Shovels
- [ ] Add a rare trade for Mowers.
- [ ] Add a trade for selling produce for currency.
