### ISSUE TITLE
[Development]: Bison

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#47]
# Overview
Found in plains biomes, this entity is territorial and will attack if the entity gets too close.
Natural predators are  Coyoties which can spawn in the same biome.

## Todo List
- [ ] Make assets for the entity
- [ ] Make the entity fight back when attacked.
- [ ] Make the entity run away if the health is at or lower than 50%
- [ ] Make the entity eat tall grass blocks to regenerate health.
- [ ] Make the entity territorial for players.
- [ ] Make Bison breed naturally.
- [ ] Make baby Bison entity
- [ ] Make Bison leather
- [ ] Make Bison ribs
