### ISSUE TITLE
[Development]: Coyote

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#48]
# Overview
Found in plains biomes, this entity is hostile to players and other entities.

## Todo List
- [ ] Make assets for the entity
- [ ] Make the entity fight back when attacked.
- [ ] Make the entity run away if the health is at or lower than 50%
- [ ] Make the entity hostile to players, Bison, and  Prairie Dogs.
- [ ] Make the entity regenerate health slowly over time.
- [ ] Make entity breed naturally.
- [ ] Make baby entities.
- [ ] Make Coyote Pelt
- [ ] Make Coyote Steak
