### ISSUE TITLE
[Development]: Prairie Dog

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#49]
# Overview
Found in plains biomes, this entity is passive to players and other entities.
Natural predators are Coyoties which can spawn in the same biome.

## Todo List
- [ ] Make assets for the entity
- [ ] Make the entity fight back when attacked.
- [ ] Make the entity run away if the health is at or lower than 50%
- [ ] Make the entity eat tall grass blocks to regenerate health.
- [ ] Make the entity passive for players and other entities.
- [ ] Make entity breed naturally.
- [ ] Make baby entities.
- [ ] Make Prairie Dog Fur
- [ ] Make Prairie Dog Chunks (Meat)
