### ISSUE TITLE
[Development]: More Stone Types

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#50]
# Overview
Add more stone types similar to Andesite, Granite, and Diorite

# Todo List
## Base Materials
- [x] Marble
- [x] Basalt
- [x] Shale

## Sub Materials
- [x] Raw
- [x] Cobbled
- [x] Mossy Cobbled
- [x] Polished
- [x] Fossil (Shale only)

## Block Types
- [x] Blocks
- [x] Stairs
- [x] Slabs
- [x] Walls
- [x] Buttons (Raw only) 
- [x] Pressure Plates (Raw only)
