### ISSUE TITLE
[Development]: Prairie Dog

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Tale-of-Biomes#88]
### Discussed in https://github.com/MCreator-Examples/Tale-of-Biomes/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **northwesttreesgaming** March 23, 2024</sup>
# Overview
Found in plains biomes, this entity is passive to players and other entities.
Natural predators are Coyoties which can spawn in the same biome.

## Todo List
- [x] Make assets for the entity
- [ ] Make the entity fight back when attacked.
- [ ] Make the entity run away if the health is at or lower than 50%
- [ ] Make the entity eat tall grass blocks to regenerate health.
- [x] Make the entity passive for players and other entities.
- [ ] Make entity breed naturally.
- [ ] Make baby entities.
- [ ] Make Prairie Dog Fur
- [ ] Make Prairie Dog Chunks (Meat)</div>
